trigger:
- main

pool:
  name: 'Default'

steps:
- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration Release
  displayName: 'Build project'

- script: dotnet test
  displayName: 'Run tests'

- script: dotnet publish --configuration Release --output publish
  displayName: 'Publish project'
